name: Run Optional Tests

# optional tests only run manually
on: workflow_dispatch

jobs:
    optional-tests:
      runs-on: lmql-ci
      steps:
          - uses: actions/checkout@v3
          - name: Setup Fresh Virtual Environment
            run: |
              pip install --upgrade pip
              python3.10 -m venv env
              export PATH=$PATH:/home/docker/.local/bin
              source env/bin/activate
              echo "VIRTUAL ENV:" $VIRTUAL_ENV
          # cache dependencies
          - name: Cache dependencies
            id: cache
            uses: corca-ai/local-cache@v2
            with:
              path: env/lib/python3.10/site-packages
              key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
              base: "/home/docker/.cache/"
          - name: Install Dependencies
            run: source env/bin/activate && pip install -e '.[hf,hf-accel,tests,llama]' && pip install langchain
          - name: Run Optional Tests
            env:
              OPENAI_API_KEY: ${{ secrets.LMQL_CI_OPENAI_KEY }}
            run: source env/bin/activate && python src/lmql/tests/all.py only optional openai langchain --failearly